server.port=7777

# TODO  choose : [kafka]/[eventBus]/[rocketMq]/[rabbitMq],recommend  [eventBus] or  [kafka]
sentinel.mq.pipeline=kafka

# todo [xxl-job] switch
sentinel.xxl.job.enabled=true

# todo choose: [apollo]/[nacos] switch  ,if [apollo] and [nacos] both false, use local.properties
sentinel.apollo.enabled=false
sentinel.nacos.enabled=true

# TODO [hades] switch
sentinel.rule.engine.enabled=true

# TODO if windows os and need upload file to send message  ,replace path !
sentinel.business.upload.crowd.path=/tmp/sentinel-upload

# TODO Whether to enable [sensitive word filter] and set the [path] of sensitive words dictionary
sentinel.senswords.filter.enabled=true
sentinel.senswords.dict.path=classpath:sensitive-words.txt

# TODO if [login use officialAccount] switch [optional], if sentinel.login.official.account.enable=true
sentinel.login.official.account.enable=false
sentinel.login.official.account.appId=${WECHAT_APP_ID:}
sentinel.login.official.account.secret=${WECHAT_APP_SECRET:}
sentinel.login.official.account.token=sentinel123

dashscope.api-key=${DASHSCOPE_API_KEY:}
