FROM eclipse-temurin:17-jre
WORKDIR /app
ENV TZ=Asia/Shanghai JAVA_OPTS=""
COPY dist/msg-service.jar /app/msg-service.jar
EXPOSE 8082
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/msg-service.jar"]
