FROM eclipse-temurin:17-jre
WORKDIR /app
ENV TZ=Asia/Shanghai JAVA_OPTS=""
COPY dist/sentinel-gateway.jar /app/sentinel-gateway.jar
EXPOSE 8080
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/sentinel-gateway.jar"]
